[tox]
env_list = poetry-check, format, lint, types, tests, coverage

[testenv]
extras = dev

[testenv:poetry-check]
skip_install = true
deps = poetry
commands = poetry check

[testenv:format]
extras = dev
commands = black --check src tests

[testenv:lint]
extras = dev
commands = pylint src tests

[testenv:types]
extras = dev
commands = mypy src

[testenv:tests]
extras = dev
commands = pytest

[testenv:coverage]
extras = dev
commands = pytest --cov=pyliner --cov-report=term-missing --cov-fail-under=90
